"use client";

import { useState } from "react";
import { getOutputs, type Output } from "./actions";

export default function OutputsClient({
  initialOutputs,
  initialTotal,
}: {
  initialOutputs: Output[];
  initialTotal: number;
}) {
  const [outputs, setOutputs] = useState<Output[]>(initialOutputs);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [total, setTotal] = useState(initialTotal);

  async function loadOutputs(nextPage: number, nextPageSize: number) {
    const data = await getOutputs(nextPage, nextPageSize);
    setOutputs(data.outputs);
    setTotal(data.total);
  }

  function changePage(nextPage: number) {
    setPage(nextPage);
    loadOutputs(nextPage, pageSize);
  }

  function changePageSize(nextPageSize: number) {
    setPageSize(nextPageSize);
    setPage(1);
    loadOutputs(1, nextPageSize);
  }

  async function downloadOutput(id: string) {
    try {
      const res = await fetch(`/api/outputs/${id}/download`);
      if (!res.ok) throw new Error("Download failed");

      const blob = await res.blob();
      const output = outputs.find((o) => o.id === id);
      const filename = output?.outputFile || `output_${id}`;

      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      alert("Download failed");
    }
  }

  const totalPages = Math.ceil(total / pageSize);
  const startIdx = (page - 1) * pageSize + 1;
  const endIdx = Math.min(page * pageSize, total);

  return (
    <div className="px-8 py-6 space-y-6 max-w-6xl">
      <div>
        <h1 className="text-xl font-semibold text-zinc-100">Generated Outputs</h1>
        <p className="text-xs text-zinc-500 mt-1">
          AI-generated documents and reports from executed actions.
        </p>
      </div>

      {outputs.length === 0 ? (
        <div className="text-center py-12">
          <p className="text-sm text-zinc-500">No outputs generated yet.</p>
          <p className="text-xs text-zinc-600 mt-1">
            Execute AI actions to generate reports, plans, and recommendations.
          </p>
        </div>
      ) : (
        <>
          <div className="bg-zinc-900 rounded-xl border border-zinc-800 overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-xs text-zinc-500 uppercase tracking-wider border-b border-zinc-800 bg-zinc-800/50">
                  <th className="px-5 py-3 font-medium">Type</th>
                  <th className="px-5 py-3 font-medium">File</th>
                  <th className="px-5 py-3 font-medium">Generated By</th>
                  <th className="px-5 py-3 font-medium">Approved By</th>
                  <th className="px-5 py-3 font-medium">Date</th>
                  <th className="px-5 py-3 font-medium text-right">Actions</th>
                </tr>
              </thead>
              <tbody>
                {outputs.map((output, i) => (
                  <tr
                    key={output.id}
                    className={`${i < outputs.length - 1 ? "border-b border-zinc-800" : ""}`}
                  >
                    <td className="px-5 py-3">
                      <span className="inline-flex items-center gap-1.5 px-2 py-1 rounded text-xs font-medium bg-zinc-800 text-zinc-300">
                        {output.actionType.replace(/_/g, " ")}
                      </span>
                    </td>
                    <td className="px-5 py-3 text-xs text-zinc-300">{output.outputFile}</td>
                    <td className="px-5 py-3 text-xs text-zinc-400">{output.generatedBy}</td>
                    <td className="px-5 py-3 text-xs text-zinc-400">{output.approvedBy}</td>
                    <td className="px-5 py-3 text-xs text-zinc-500">
                      {new Date(output.createdAt).toLocaleDateString()}
                    </td>
                    <td className="px-5 py-3 text-right">
                      <button
                        onClick={() => downloadOutput(output.id)}
                        className="text-xs text-blue-400 hover:text-blue-300 transition-colors"
                      >
                        Download
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          <div className="flex items-center justify-between text-xs text-zinc-500">
            <div className="flex items-center gap-2">
              <span>Rows per page:</span>
              <select
                value={pageSize}
                onChange={(e) => changePageSize(parseInt(e.target.value, 10))}
                className="bg-zinc-800 border border-zinc-700 rounded px-2 py-1 text-zinc-300"
              >
                <option value={10}>10</option>
                <option value={25}>25</option>
                <option value={50}>50</option>
              </select>
            </div>
            <span>
              {total === 0 ? "No outputs" : `Showing ${startIdx}–${endIdx} of ${total}`}
            </span>
            <div className="flex gap-2">
              <button
                onClick={() => changePage(Math.max(1, page - 1))}
                disabled={page === 1}
                className="px-3 py-1 bg-zinc-800 border border-zinc-700 rounded hover:bg-zinc-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                Prev
              </button>
              <span className="px-3 py-1 text-xs text-zinc-400">
                {page} / {totalPages}
              </span>
              <button
                onClick={() => changePage(Math.min(totalPages, page + 1))}
                disabled={page >= totalPages}
                className="px-3 py-1 bg-zinc-800 border border-zinc-700 rounded hover:bg-zinc-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                Next
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
